### ISSUE TITLE
Namespace

### ISSUE THREAD

**Issue by Nek-** [KnpLabs/php-json-schema#2]
Hello,

This project looks interesting but most projects are using the namespace `KnpLabs`. I have no idea if the namespace change (which is `Knp` on this project) is on purpose or just a mistake. So I notice it here. Sorry for the noise if it's done on purpose.

**Comment by AntoineLelaisant** [comment]
Hello ! 

Indeed it sounds a bit inconsistent :sweat_smile: thanks for spotting it! I will try to push an update during the week to fix this.
