### ISSUE TITLE
can you provide an example that shows how to validate something?

### ISSUE THREAD

**Issue by michabbb** [KnpLabs/php-json-schema#3]
thanks !

**Comment by AntoineLelaisant** [comment]
Hello ! We introduced a Validator implementation (based on [swaggest/json-schema](https://github.com/swaggest/php-json-schema)) in the Symfony Bundle [KnpLabs/php-json-schema-bundle](https://github.com/KnpLabs/php-json-schema-bundle). You can find it [here](https://github.com/KnpLabs/php-json-schema-bundle/blob/master/src/Validator/SwaggestValidator.php). 

Then the usage is pretty simple:

Let's say you have the following schema: 
```php
<?php

namespace Acme;

use Knp\JsonSchema\ObjectSchema;
use Knp\JsonSchema\Scalar\UuidSchema;

class AcmeSchema extends ObjectSchema
{
    public function __construct()
    {
        $this->addProperty('id', new UuidSchema());
    }

    public function getTitle(): string
    {
        return 'Acme';
    }

    public function getDescription(): string
    {
        return 'Acme description';
    }
}
```

Then anywhere in your code you can do: 

```php
use Knp\JsonSchemaBundle\Validator\SwaggestValidator;

$validator = new SwaggestValidator();

$data = ['id' => 'ea7bae92-78b9-473a-83bc-a0e5a3869ebe'];

$errors = $validator->validate($data, new AcmeSchema());
``` 

`$errors` will be either `null` if there is no raised errors or an instance of `Knp\JsonSchema\Validator\Errors`.

**Comment by AntoineLelaisant** [comment]
Btw implementing the SwaggestValidator right into this library is something we can consider if you wish to use it without the Symfony bundle. Please let me know if it is something that could help. In any case we really have to write more documentation :smile:.

**Comment by michabbb** [comment]
thanks a lot, just wanted to know, having schemas without validation makes no sense, that's why I had to ask 😉
